version: "3.7"
services:
    nginx:
        build:
            context: ./requirements/nginx
        volumes:
            - ./data/WordPress:/var/lib/nginx/html
        expose:
            - 443
        ports:
            - "433:433"
        restart: always
        depends_on:
            - wordpress
        networks:
            - jonghopa
    wordpress:
        build:
            context: ./requirements/wordpress
        volumes:
            - ./data/WordPress:/var/lib/nginx/html
        expose:
            - 9000
        restart: always
        depends_on:
            - mariadb
        networks:
            - jonghopa
    mariadb:
        build:
            context: ./requirements/mariadb
        volumes:
            - ./data/DB:/var/lib/mysql
        expose:
            - 3306
        restart: always
        networks:
            - jonghopa

networks:
    jonghopa:
        driver: bridge
