version: "3.7"
services:
    nginx:
        build:
            context: ./requirements/nginx
        volumes:
            - data/WordPress:/var/lib/nginx/html
        expose:
            - 443
        ports:
            - "433:433"
        depends_on:
            - php-fpm
        network:
            - jonghopa
    wordpress:
        build:
            context: ./requirements/wordpress
        volumes:
            - data/WordPress:/var/lib/nginx/html
        expose:
            - 9000
        depends_on:
            - mariadb
        network:
            - jonghopa
    mariadb:
        build:
            context: ./requirements/mariadb
        volumes:
            - ./data/DB:/var/lib/mysql
        expose:
            - 3306
        network:
            - jonghopa

network:
    jonghopa:
        driver: bridge
