services:
    nginx:
        container_name: nginx
        build:
            context: ./requirements/nginx
        volumes:
            - ft_wp:/var/lib/nginx/html
        expose:
            - 443
        ports:
            - "443:443"
        restart: always
        depends_on:
            - wordpress
        networks:
            - jonghopa
    wordpress:
        container_name: wordpress
        build:
            context: ./requirements/wordpress
        environment:
            ROOT_DIRECTORY: ${WEBSERV_ROOT_DIRECTORY}
            PHP_FPM_CONF_FILE: ${PHP_FPM_CONF_FILE}
            PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
            PHP_MAX_UPLOAD: ${PHP_MAX_UPLOAD}
            PHP_MAX_FILE_UPLOAD: ${PHP_MAX_FILE_UPLOAD}
            PHP_MAX_POST: ${PHP_MAX_POST}
            PHP_DISPLAY_ERRORS: ${PHP_DISPLAY_ERRORS}
            PHP_DISPLAY_STARTUP_ERRORS: ${PHP_DISPLAY_STARTUP_ERRORS}
            PHP_ERROR_REPORTING: ${PHP_ERROR_REPORTING}
            PHP_CGI_FIX_PATHINFO: ${PHP_CGI_FIX_PATHINFO}
            PHP_INI_FILE: ${PHP_INI_FILE}
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
            WORDPRESS_DB_HOSTNAME: ${WORDPRESS_DB_HOSTNAME}
            LANGUAGE_CODE: ${LANGUAGE_CODE}
            WORDPRESS_SITE_URL: ${WORDPRESS_SITE_URL}
            WORDPRESS_SITE_NAME: ${WORDPRESS_SITE_NAME}
            WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
            WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
            WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
            WORDPRESS_NORMAL_USER: ${WORDPRESS_NORMAL_USER}
            WORDPRESS_NORMAL_USER_EMAIL: ${WORDPRESS_NORMAL_USER_EMAIL}
            WORDPRESS_NORMAL_USER_PASSWORD: ${WORDPRESS_NORMAL_USER_PASSWORD}
        volumes:
            - ft_wp:/var/lib/nginx/html
        depends_on:
            - mariadb
        expose:
            - 9000
        restart: always
        networks:
            - jonghopa
    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb
        environment:
            MYSQL_ROOT_NAME: ${MYSQL_ROOT_NAME}
            MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
            MYSQL_DATABASE_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
            MYSQL_USER_NAME: ${MYSQL_USER_NAME}
            MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
        volumes:
            - ft_db:/var/lib/mysql
        expose:
            - 3306
        restart: always
        networks:
            - jonghopa

volumes:
  ft_wp:
    name: ft_wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jonghopa/data/wp/
  ft_db:
    name: ft_db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jonghopa/data/db/

networks:
    jonghopa:
        driver: bridge
